//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VaultSync.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to move ALL items from computer &apos;{0}&apos; to &apos;{1}&apos;?.
        /// </summary>
        internal static string AskHostMove {
            get {
                return ResourceManager.GetString("AskHostMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract to the original folder?.
        /// </summary>
        internal static string AskIfExtractToOriginalFolder {
            get {
                return ResourceManager.GetString("AskIfExtractToOriginalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault &quot;{0}&quot; doesn&apos;t exist. Create it?.
        /// </summary>
        internal static string AskToCreateVault {
            get {
                return ResourceManager.GetString("AskToCreateVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits: {0}.
        /// </summary>
        internal static string Bits {
            get {
                return ResourceManager.GetString("Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptographicException error: .
        /// </summary>
        internal static string CryptographicException {
            get {
                return ResourceManager.GetString("CryptographicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VaultSync is already running. Stopping to prevent data corruption..
        /// </summary>
        internal static string DuplicateProcess {
            get {
                return ResourceManager.GetString("DuplicateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with folder {0} : {1} : {2}.
        /// </summary>
        internal static string EnumerateDirectoryFailed {
            get {
                return ResourceManager.GetString("EnumerateDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} KB.
        /// </summary>
        internal static string FileSizeFormat {
            get {
                return ResourceManager.GetString("FileSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create folder in DB.
        /// </summary>
        internal static string FolderCreateFailed {
            get {
                return ResourceManager.GetString("FolderCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other button types not implemented.
        /// </summary>
        internal static string OtherButtonsUnimplemented {
            get {
                return ResourceManager.GetString("OtherButtonsUnimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available space is running out. The sync has been cancelled..
        /// </summary>
        internal static string OutOfSpace {
            get {
                return ResourceManager.GetString("OutOfSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password change failed. Use the previous password. Error: {0}.
        /// </summary>
        internal static string PasswordChangeFailed {
            get {
                return ResourceManager.GetString("PasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault Sync.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured and file {0} has not been stored. Error {1}.
        /// </summary>
        internal static string SyncFailure {
            get {
                return ResourceManager.GetString("SyncFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many failed attempts to open the database.
        /// </summary>
        internal static string TooManyAttempts {
            get {
                return ResourceManager.GetString("TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the application is available. Use the link below to download the latest Setup.exe..
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the website for an update..
        /// </summary>
        internal static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update check failed to extract the latest version number. Please check the website..
        /// </summary>
        internal static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update check failed to connect to the website..
        /// </summary>
        internal static string UpdateCheckWebException {
            get {
                return ResourceManager.GetString("UpdateCheckWebException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installed application is the latest version..
        /// </summary>
        internal static string UpdateNotRequired {
            get {
                return ResourceManager.GetString("UpdateNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remember the View Type.
        /// </summary>
        internal static string UpdateViewTypeFailed {
            get {
                return ResourceManager.GetString("UpdateViewTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a new vault at {0}. Check permissions..
        /// </summary>
        internal static string VaultCreateFailure {
            get {
                return ResourceManager.GetString("VaultCreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/projects/vaultsync/files.
        /// </summary>
        internal static string VersionCheckURL {
            get {
                return ResourceManager.GetString("VersionCheckURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
